// This file was automatically generated by the pas2jni utility.
// Do not edit this file.
package pas;

import pas.system.*;

public class personmodel {
  static { pas.system.InitJni(); }

  /* class Tperson */
  public static class Tperson extends TObject {
    public Tperson(PascalObject obj) { super(obj); }
    public Tperson(long objptr) { super(objptr); }
    // constructor Create(firstName: ansistring; middleName: ansistring; lastName: ansistring): Tperson
    public native static Tperson Create(String firstName, String middleName, String lastName);
    public static Tperson Class() { return new Tperson(system.GetClassRef(1)); }
    public static system.TClass TClass() { return system.GetTClass(1); }
    // function getFirstName: ansistring
    public native String getFirstName();
    // function getMiddleName: ansistring
    public native String getMiddleName();
    // function getLastName: ansistring
    public native String getLastName();
    // function format: ansistring
    public native String format();
    // procedure setFirstName(firstName: ansistring)
    public native void setFirstName(String firstName);
    // procedure setMiddleName(middleName: ansistring)
    public native void setMiddleName(String middleName);
    // procedure setLastName(lastName: ansistring)
    public native void setLastName(String lastName);
  }

}
